### ISSUE TITLE
[Bug] 2captcha error

### ISSUE THREAD

**Issue by vinsilsim** [sriyegna/Pikaptcha#12]
Everything works normally without using 2captcha. When I use the 2captcha got this error:

Attempting to create user speglachslug:xxxxxxx. Opening browser...
Traceback (most recent call last):
  File "C:\Python27\Scripts\pikaptcha-script.py", line 9, in <module>
    load_entry_point('Pikaptcha==0.1', 'console_scripts', 'pikaptcha')()
  File "c:\python27\lib\site-packages\pikaptcha\console.py", line 96, in entry
    account_info = pikaptcha.random_account(args.username, args.password, args.e
mail, args.birthday, args.plusmail, args.recaptcha)
  File "c:\python27\lib\site-packages\pikaptcha\accountcreator.py", line 244, in
 random_account
    account_created = create_account(try_username, password, try_email, try_birt
hday, captchakey2)
  File "c:\python27\lib\site-packages\pikaptcha\accountcreator.py", line 115, in
 create_account
    driver = webdriver.PhantomJS(desired_capabilities=dcap)
  File "c:\python27\lib\site-packages\selenium\webdriver\phantomjs\webdriver.py"
, line 52, in **init**
    self.service.start()
  File "c:\python27\lib\site-packages\selenium\webdriver\common\service.py", lin
e 71, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'phantomjs' executable n
eeds to be in PATH.

Exception AttributeError: "'Service' object has no attribute 'process'" in <boun
d method Service.__del__ of <selenium.webdriver.phantomjs.service.Service object
 at 0x00000000044D7908>> ignored

**Comment by sriyegna** [comment]
You didn't install phantomjs. Read the readme section on 2captcha.
