### ISSUE TITLE
problem with run

### ISSUE THREAD

**Issue by vinsilsim** [sriyegna/Pikaptcha#2]
Traceback (most recent call last):
  File "/usr/local/bin/pikaptcha", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 2953, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2939, in _call_aside
    f(_args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2966, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 635, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 943, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 829, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pyasn1; extra == "security"' distribution was not found and is required by requests

anyone can help me solve?

**Comment by sriyegna** [comment]
I cannot say for sure but I think something is messed up with your python. Perhaps reinstall it. What environment are you running in? Is this error consistent?
