### ISSUE TITLE
Generic exception

### ISSUE THREAD

**Issue by FranManre** [sriyegna/Pikaptcha#24]
2 days ago it was working perfectly, yesterday i started getting this error:

```
Accepted Terms of Service for ********
Generic Exception: Traceback (most recent call last):
  File "c:\python27\lib\site-packages\pikaptcha\console.py", line 166, in entry
    email_verify(args.plusmail, args.googlepass)
  File "c:\python27\lib\site-packages\pikaptcha\gmailv.py", line 43, in email_verify
    M = imaplib.IMAP4_SSL('imap.gmail.com')
  File "c:\python27\lib\imaplib.py", line 1166, in __init__
    IMAP4.__init__(self, host, port)
  File "c:\python27\lib\imaplib.py", line 173, in __init__
    self.open(host, port)
  File "c:\python27\lib\imaplib.py", line 1178, in open
    self.sslobj = ssl.wrap_socket(self.sock, self.keyfile, self.certfile)
  File "c:\python27\lib\ssl.py", line 933, in wrap_socket
    ciphers=ciphers)
  File "c:\python27\lib\ssl.py", line 601, in __init__
    self.do_handshake()
  File "c:\python27\lib\ssl.py", line 830, in do_handshake
    self._sslobj.do_handshake()
SSLEOFError: EOF occurred in violation of protocol (_ssl.c:590)
```

After tried to get rid of it, just reinstalled everything from python to pikaptcha, had another error caused by yesterdays update, but today i reinstalled all once more and now im getting the same error.
afaik no1 have same error, or is not reported, any clue? please help!

**Solution:**
After doing this all, ive just shutdown smart security's firewall and it started to work, dunno why it have blocked pikaptcha, ill leave this here to help someone is having same issue.
![smarts](https://cloud.githubusercontent.com/assets/20927872/17968324/801fd606-6acc-11e6-8432-0346d9b7d79a.png)

**Comment by sriyegna** [comment]
It doesn't block pikaptcha. It blocks your SSL connection to gmail. Thanks for fixing and posting your fix
