### ISSUE TITLE
Error: pkg_resources.DistributionNotFound: selenium==2.53.6

### ISSUE THREAD

**Issue by MrAwesomers** [sriyegna/Pikaptcha#33]
Hello, I'm a noob when it comes to stuff like this. I've googled but couldn't find an answer. Could someone point me towards a solution please?

When trying to run "pikaptcha -u accountnames -c 100  -p accountpass -m myemail@gmail.com -av True -gp GooglePass -r CaptchaAPIKey" I get the following error:

Traceback (most recent call last):
  File "/usr/local/bin/pikaptcha", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2793, in <module>
    working_set.require(**requires**)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 673, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 576, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: selenium==2.53.6

Anyone know what's causing this?

**Comment by sriyegna** [comment]
Looks like selenium wasn't installed. In cmd, type
pip install selenium
Then try

Alternatively, download requirements.txt from the github and run
pip install requirements.txt

It's possible you are missing a bunch of things. These are not really issues with the script but rather the decencies. No idea why it doesn't install
