### ISSUE TITLE
WebDriverException

### ISSUE THREAD

**Issue by Titi9237** [sriyegna/Pikaptcha#49]
Hi,
I'm trying to use your software with Ubuntu 16.04.
After completing the installation (as in the Readme), I get this error : 
`Making account #1
Attempting to create user tenkcrokblift:glussslurhuss. Opening browser...
Generic Exception: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pikaptcha/console.py", line 159, in entry
    account_info = pikaptcha.random_account(username, args.password, args.email, args.birthday, args.plusmail, args.recaptcha, args.captchatimeout)
  File "/usr/local/lib/python2.7/dist-packages/pikaptcha/accountcreator.py", line 231, in random_account
    account_created = create_account(try_username, password, try_email, try_birthday, captchakey2, captchatimeout)
  File "/usr/local/lib/python2.7/dist-packages/pikaptcha/accountcreator.py", line 94, in create_account
    driver = webdriver.Chrome()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 62, in **init**
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 71, in start
    os.path.basename(self.path), self.start_error_message)
WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

Exception AttributeError: "'Service' object has no attribute 'process'" in <bound method Service.__del__ of <selenium.webdriver.chrome.service.Service object at 0x7fb90ac728d0>> ignored
`
Is there any way to fix this ?

Regards

**Comment by sriyegna** [comment]
You do not have chrome driver
