### ISSUE TITLE
WebDriverException: Message: session not created exception

### ISSUE THREAD

**Issue by kuntau** [sriyegna/Pikaptcha#52]
Hi guys
I need help with this error.. any idea why?

```
➜ pikaptcha
Making account #1
Attempting to create user frezclagspust:plonkviftswost. Opening browser...
Generic Exception: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pikaptcha/console.py", line 159, in entry
    account_info = pikaptcha.random_account(username, args.password, args.email, args.birthday, args.plusmail, args.recaptcha, args.captchatimeout)
  File "/usr/local/lib/python2.7/site-packages/pikaptcha/accountcreator.py", line 231, in random_account
    account_created = create_account(try_username, password, try_email, try_birthday, captchakey2, captchatimeout)
  File "/usr/local/lib/python2.7/site-packages/pikaptcha/accountcreator.py", line 94, in create_account
    driver = webdriver.Chrome()
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 90, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 177, in start_session
    response = self.execute(Command.NEW_SESSION, capabilities)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: session not created exception
from unknown error: Runtime.evaluate missing 'wasThrown'
  (Session info: chrome=54.0.2840.16)
  (Driver info: chromedriver=2.23.409710 (0c4084804897ac45b5ff65a690ec6583b97225c0),platform=Mac OS X 10.11.6 x86_64)
```

**Comment by radiantradon** [comment]
I had this issue running an older version of chromedriver with an updated version of Chrome, the problem went away when I downloaded and installed the newest version of chromedriver. Hope that helps.
