### ISSUE TITLE
Error while using -r recaptchacode command

### ISSUE THREAD

**Issue by init-andrea** [sriyegna/Pikaptcha#53]
This is the error i get and i have no idea of how to fix it.

Your 2captcha balance is: 9.51912
This run will cost you approximately: 0.003
Making account #1
Attempting to create user ciaosonotuo:tayfloftdrank. Opening browser...
Generic Exception: Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\pikaptcha\console.py", line 159, in entry
    account_info = pikaptcha.random_account(username, args.password, args.email, args.birthday, args.plusmail, args.recaptcha, args.captchatimeout)
  File "C:\Python27\lib\site-packages\pikaptcha\accountcreator.py", line 231, in random_account
    account_created = create_account(try_username, password, try_email, try_birthday, captchakey2, captchatimeout)
  File "C:\Python27\lib\site-packages\pikaptcha\accountcreator.py", line 92, in create_account
    driver = webdriver.PhantomJS(desired_capabilities=dcap)
  File "C:\Python27\lib\site-packages\selenium\webdriver\phantomjs\webdriver.py", line 52, in **init**
    self.service.start()
  File "C:\Python27\lib\site-packages\selenium\webdriver\common\service.py", line 71, in start
    os.path.basename(self.path), self.start_error_message)
WebDriverException: Message: 'phantomjs' executable needs to be in PATH.

Exception AttributeError: "'Service' object has no attribute 'process'" in <bound method Service.__del__ of <selenium.webdriver.phantomjs.service.Service object at 0x048923D0>> ignored

**Comment by antiremy** [comment]
Make sure nodejs is installed then run `npm install phantomjs`
