### ISSUE TITLE
Error while account creation - Browser closes itself immediately.

### ISSUE THREAD

**Issue by garygrossgarten** [sriyegna/Pikaptcha#67]
`Making account #1
Attempting to create user robsmushsluss:nunslazclunk. Opening browser...
Generic Exception: Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pikaptcha/console.py", line 159, in entry
    account_info = pikaptcha.random_account(username, args.password, args.email, args.birthday, args.plusmail, args.recaptcha, args.captchatimeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pikaptcha/accountcreator.py", line 231, in random_account
    account_created = create_account(try_username, password, try_email, try_birthday, captchakey2, captchatimeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pikaptcha/accountcreator.py", line 95, in create_account
    driver.set_window_size(600, 600)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 846, in set_window_size
    'windowHandle': windowHandle})
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: cannot get automation extension
from unknown error: bad inspector message: {"method":"Page.loadEventFired","params":{"timestamp":1167,257076}}
  (Session info: chrome=54.0.2840.71)
  (Driver info: chromedriver=2.25.426935 (820a95b0b81d33e42712f9198c215f703412e1a1),platform=Mac OS X 10.11.6 x86_64)`

I get this error when trying to create accounts with manual captcha resolving. The browser closes immediately after it was opened by pikaptcha.

**Comment by kamaze** [comment]
@garygrossgarten please check https://github.com/sriyegna/Pikaptcha/pull/63#issue-187590718,
it works for me.

**Comment by CreativiTimothy** [comment]
Check out my pull request. I put the updated link for the chrome driver which is required for Pikaptcha to work (the old link the README doesn't work)

**Comment by garygrossgarten** [comment]
@kamaze @CreativiTimothy     i tried that and as you can see in the logs I'm using the latest version of the chromedriver. Driver info: chromedriver=2.25.426935. BTW I'm working on a Mac

**Comment by JoyQu** [comment]
I had updated the new version chromedriver , but still doesn't work when it verfiy the email,
what's wrong with me

Trying to accept Terms of Service for swossstragvunk.
Generic Exception: Traceback (most recent call last):
  File "c:\python27\lib\site-packages\pikaptcha\console.py", line 166, in entry
    accept_tos(account_info["username"], account_info["password"], args.location
, args.proxy)
  File "c:\python27\lib\site-packages\pikaptcha\tos.py", line 10, in accept_tos
    accept_tos_helper(username, password, location, proxy)
  File "c:\python27\lib\site-packages\pikaptcha\tos.py", line 32, in accept_tos_
helper
    response = api.app_simulation_login()
  File "c:\python27\lib\site-packages\pgoapi\pgoapi.py", line 169, in app_simula
tion_login
    response = request.call()
  File "c:\python27\lib\site-packages\pgoapi\pgoapi.py", line 245, in call
    request.activate_signature(signature_lib_path, hash_lib_path)
  File "c:\python27\lib\site-packages\pgoapi\rpc_api.py", line 85, in activate_s
ignature
    self._signature_lib = ctypes.cdll.LoadLibrary(signature_lib_path)
  File "c:\python27\lib\ctypes__init__.py", line 440, in LoadLibrary
    return self._dlltype(name)
  File "c:\python27\lib\ctypes__init__.py", line 362, in **init**
    self._handle = _dlopen(self._name, mode)
TypeError: expected string or Unicode object, NoneType found

**Comment by jane0815** [comment]
Same problem here on Mac OSX. Browser closes automatically. 

Chromedriver: 2.25.426935
