### ISSUE TITLE
Error handler?

### ISSUE THREAD

**Issue by WJKH** [sriyegna/Pikaptcha#7]
First of all, great work and thank you for make it public.

I was running it and found the following error then the program stopped.
The error come from the HTTP server, but maybe you can add an error handler to avoid program stops on error.

```
Making account #27
Attempting to create user xxx:xxx. Opening browser...
Step 1: Verifying age using birthday: 1983-05-19
Step 2: Entering account details
Starting autosolve recaptcha
Traceback (most recent call last):
  File "C:\Python27\Scripts\pikaptcha-script.py", line 9, in <module>
    load_entry_point('Pikaptcha==0.1', 'console_scripts', 'pikaptcha')()
  File "c:\python27\lib\site-packages\pikaptcha\console.py", line 96, in entry
    account_info = pikaptcha.random_account(args.username, args.password, args.email, args.birthday, args.plusmail, args.recaptcha)
  File "c:\python27\lib\site-packages\pikaptcha\accountcreator.py", line 241, in random_account
    account_created = create_account(try_username, password, try_email, try_birthday, captchakey2)
  File "c:\python27\lib\site-packages\pikaptcha\accountcreator.py", line 176, in create_account
    recaptcharesponse = urllib2.urlopen("http://2captcha.com/in.php?key=" + captchakey2 + "&method=userrecaptcha&googlekey=" + gkey).read()
  File "c:\python27\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "c:\python27\lib\urllib2.py", line 435, in open
    response = meth(req, response)
  File "c:\python27\lib\urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "c:\python27\lib\urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "c:\python27\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "c:\python27\lib\urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 500:
```

**Comment by sriyegna** [comment]
You are correct, that should be handled. I will fix it soon.

**Comment by WJKH** [comment]
Found another error.
By the way... 2captcha is really SLOW!

```
Making account #29
Attempting to create user xxx:xxx. Opening browser...
Step 1: Verifying age using birthday: 1987-11-27
Step 2: Entering account details
Starting autosolve recaptcha
We will wait 10 seconds for captcha to be solved by 2captcha
Captcha still not solved, waiting another 10 seconds.
Captcha still not solved, waiting another 10 seconds.
Captcha still not solved, waiting another 10 seconds.
Captcha still not solved, waiting another 10 seconds.
Captcha still not solved, waiting another 10 seconds.
Captcha still not solved, waiting another 10 seconds.
Traceback (most recent call last):
  File "C:\Python27\Scripts\pikaptcha-script.py", line 9, in <module>
    load_entry_point('Pikaptcha==0.1', 'console_scripts', 'pikaptcha')()
  File "c:\python27\lib\site-packages\pikaptcha\console.py", line 96, in entry
    account_info = pikaptcha.random_account(args.username, args.password, args.email, args.birthday, args.plusmail, args.recaptcha)
  File "c:\python27\lib\site-packages\pikaptcha\accountcreator.py", line 241, in random_account
    account_created = create_account(try_username, password, try_email, try_birthday, captchakey2)
  File "c:\python27\lib\site-packages\pikaptcha\accountcreator.py", line 188, in create_account
    elem = driver.find_element_by_name("g-recaptcha-response")
  File "c:\python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 365, in find_element_by_name
    return self.find_element(by=By.NAME, value=name)
  File "c:\python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 752, in find_element
    'value': value})['value']
  File "c:\python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "c:\python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: {"errorMessage":"Unable to find element with name 'g-recaptcha-response'","request":{"headers":{"Accept":"application/json","Accept-Encoding
":"identity","Connection":"close","Content-Length":"103","Content-Type":"application/json;charset=UTF-8","Host":"127.0.0.1:65246","User-Agent":"Python-urllib/2.7"},"httpVersion":"1.1","method":"POST",
"post":"{\"using\": \"name\", \"sessionId\": \"8ab12ef0-6871-11e6-ae45-1120bbd1614d\", \"value\": \"g-recaptcha-response\"}","url":"/element","urlParsed":{"anchor":"","query":"","file":"element","dire
ctory":"/","path":"/element","relative":"/element","port":"","host":"","password":"","user":"","userInfo":"","authority":"","protocol":"","source":"/element","queryKey":{},"chunks":["element"]},"urlOr
iginal":"/session/8ab12ef0-6871-11e6-ae45-1120bbd1614d/element"}}
Screenshot: available via screen


C:\Users\Administrator\Desktop>
```

**Comment by sriyegna** [comment]
First error should be handled now. I believe second error should also be handled but I don't know how to reproduce your situation to test.

**Comment by bbdoc** [comment]
Hello,

I'm also getting an error trying to run pikaptcha using -r : 

```
Making account #1
Attempting to create user stactspizswid:pokego1204. Opening browser...
Step 1: Verifying age using birthday: 1986-04-02
Step 2: Entering account details
Starting autosolve recaptcha
We will wait 10 seconds for captcha to be solved by 2captcha
Captcha still not solved, waiting another 10 seconds.
Generic Exception: Traceback (most recent call last):
  File "c:\python27\lib\site-packages\pikaptcha\console.py", line 159, in entry
    account_info = pikaptcha.random_account(username, args.password, args.email, args.birthday, args.plusmail, args.recaptcha, args.captchatimeout)
  File "c:\python27\lib\site-packages\pikaptcha\accountcreator.py", line 231, in random_account
    account_created = create_account(try_username, password, try_email, try_birthday, captchakey2, captchatimeout)
  File "c:\python27\lib\site-packages\pikaptcha\accountcreator.py", line 179, in create_account
    elem = driver.find_element_by_name("g-recaptcha-response")
  File "c:\python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 365, in find_element_by_name
    return self.find_element(by=By.NAME, value=name)
  File "c:\python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 752, in find_element
    'value': value})['value']
  File "c:\python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "c:\python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: {"errorMessage":"Unable to find element with name 'g-recaptcha-response'","request":{"headers":{"Accept":"application/json","Accept-Encoding":"identity","Connection":"close","Content-Length":"103","Content-Type":"application/json;charset=UTF-8","Host":"127.0.0.1:54273","User-Agent":"Python-urllib/2.7"},"httpVersion":"1.1","method":"POST","post":"{\"using\": \"name\", \"sessionId\": \"afc3de10-ae98-11e6-9f92-7fa4b35f1534\", \"value\": \"g-recaptcha-response\"}","url":"/element","urlParsed":{"anchor":"","query":"","file":"element","directory":"/","path":"/element","relative":"/element","port":"","host":"","password":"","user":"","userInfo":"","authority":"","protocol":"","source":"/element","queryKey":{},"chunks":["element"]},"urlOriginal":"/session/afc3de10-ae98-11e6-9f92-7fa4b35f1534/element"}}
Screenshot: available via screen
```

Can you help ?
Thanks
