### ISSUE TITLE
TypeError: expected string or Unicode object, NoneType found

### ISSUE THREAD

**Issue by Kuju29** [sriyegna/Pikaptcha#71]
Generic Exception: Traceback (most recent call last):
  File "c:\python27\lib\site-packages\pikaptcha\console.py", line 166, in entry
    accept_tos(account_info["username"], account_info["password"], args.location, args.proxy)
  File "c:\python27\lib\site-packages\pikaptcha\tos.py", line 10, in accept_tos
    accept_tos_helper(username, password, location, proxy)
  File "c:\python27\lib\site-packages\pikaptcha\tos.py", line 32, in accept_tos_helper
    response = api.app_simulation_login()
  File "c:\python27\lib\site-packages\pgoapi\pgoapi.py", line 169, in app_simulation_login
    response = request.call()
  File "c:\python27\lib\site-packages\pgoapi\pgoapi.py", line 245, in call
    request.activate_signature(signature_lib_path, hash_lib_path)
  File "c:\python27\lib\site-packages\pgoapi\rpc_api.py", line 85, in activate_signature
    self._signature_lib = ctypes.cdll.LoadLibrary(signature_lib_path)
  File "c:\python27\lib\ctypes__init.py", line 440, in LoadLibrary
    return self._dlltype(name)
  File "c:\python27\lib\ctypes\init.py", line 362, in init__
    self._handle = _dlopen(self._name, mode)
TypeError: expected string or Unicode object, NoneType found

**Comment by Kuju29** [comment]
pip install --upgrade git+https://github.com/keyphact/pgoapi.git

**Comment by Kuju29** [comment]
https://sites.google.com/a/chromium.org/chromedriver/downloads

**Comment by plan291037** [comment]
-u  -p -m  -sn  -c  -b  -r -it(-t) -av True -gp
