### ISSUE TITLE
Failed to create user

### ISSUE THREAD

**Issue by ivar111** [sriyegna/Pikaptcha#74]
I've been using pikaptcha for a while now and suddenly it's not creating accounts. This is run on Ubuntu. i'm running the same command as always, no settings have changed. I tried removing Pikaptcha and retry it.
It runs everything fine. I get to manually do the captcha, then it just says Failed to create user: XX and tries to create another user which also fails. It also fails when using 2captcha.

Don't know if this traceback is of any help.

Traceback (most recent call last):
  File "/usr/local/bin/pikaptcha", line 11, in <module>
    load_entry_point('Pikaptcha==0.1', 'console_scripts', 'pikaptcha')()
  File "/usr/local/lib/python2.7/dist-packages/pikaptcha/console.py", line 159, in entry
    account_info = pikaptcha.random_account(username, args.password, args.email, args.birthday, args.plusmail, args.recaptcha, args.captchatimeout)
  File "/usr/local/lib/python2.7/dist-packages/pikaptcha/accountcreator.py", line 231, in random_account
    account_created = create_account(try_username, password, try_email, try_birthday, captchakey2, captchatimeout)
  File "/usr/local/lib/python2.7/dist-packages/pikaptcha/accountcreator.py", line 184, in create_account
    user.submit()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webelement.py", line 83, in submit
    self._execute(Command.SUBMIT_ELEMENT)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webelement.py", line 461, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 234, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/remote_connection.py", line 401, in execute
    return self._request(command_info[0], url, body=data)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/remote_connection.py", line 433, in _request
    resp = self._conn.getresponse()
  File "/usr/lib/python2.7/httplib.py", line 1136, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 409, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)

**Comment by Stuck7hrottle** [comment]
Does the first one work? I have the same issue, but only after the first account is created. Sort of looks like there is now a cool down on account creation from the same IP.

**Comment by ivar111** [comment]
It seems to be an update on Pokemon trainer club account creation site, the password field now needs special characters.
