### ISSUE TITLE
Chrome opens and closes.

### ISSUE THREAD

**Issue by Rootkit-** [sriyegna/Pikaptcha#87]
> C:\Users\secret\Desktop\Pikaptcha-master>pikaptcha -p asdf1234$ -m sexyjakexx@gmail.com
Making account #1
Attempting to create user shipplompfrast:secret$. Opening browser...
Generic Exception: Traceback (most recent call last):
  File "c:\python27\lib\site-packages\pikaptcha\console.py", line 162, in entry
    account_info = pikaptcha.random_account(username, args.password, args.email, args.birthday, args.plusmail, args.recaptcha, args.captchatimeout)
  File "c:\python27\lib\site-packages\pikaptcha\accountcreator.py", line 231, in random_account
    account_created = create_account(try_username, password, try_email, try_birthday, captchakey2, captchatimeout)
  File "c:\python27\lib\site-packages\pikaptcha\accountcreator.py", line 94, in create_account
    driver = webdriver.Chrome()
  File "c:\python27\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 69, in __init__
    desired_capabilities=desired_capabilities)
  File "c:\python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 90, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "c:\python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 177, in start_session
    response = self.execute(Command.NEW_SESSION, capabilities)
  File "c:\python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "c:\python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: session not created exception
from unknown error: Runtime.executionContextCreated has invalid 'context': {"auxData":{"frameId":"5648.1","isDefault":true},"id":1,"name":"","origin":"://"}
  (Session info: chrome=55.0.2883.87)
  (Driver info: chromedriver=2.23.409699 (49b0fa931cda1caad0ae15b7d1b68004acd05129),platform=Windows NT 6.3.9600 x86_64)

So chrome opens then closes and gives this error
I'm running pikaptcha -p secret$ -m secret@gmail.com (password is longer i hid it.)

I have everything installed and I'm highly tech savvy.

**Comment by Boby360** [comment]
A) the plus mail trick i dont think works with gmail anymore. and B) It looks like a chromedriver issue. You need to update to the newest version. Which is not the version in the readme. You can refer to #63

**Comment by Rootkit-** [comment]
Ok well I reinstalled the latest chromedriver, I also ran npm install phantomjs, and npm install it didn't start working till I rebooted. I also used a outlook account and just manually accepted stuff. I added coordinates for accepting TOS
