### ISSUE TITLE
Mac - ImportError: No module named seleniumrequests

### ISSUE THREAD

**Issue by georgeherby** [sriyegna/Pikaptcha#92]
Installed on Mac but not working i followed the steps:
- Open terminal and install chromedriver by typing brew install chromedriver
- In terminal type pip install git+https://github.com/sriyegna/pikaptcha without quotations and hit enter

But when i run Pikaptcha in terminal i get the below issues..

Traceback (most recent call last):
  File "/usr/local/bin/pikaptcha", line 11, in <module>
    load_entry_point('Pikaptcha==0.1', 'console_scripts', 'pikaptcha')()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 560, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2642, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2296, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2302, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/site-packages/pikaptcha/__init__.py", line 1, in <module>
    from pikaptcha.accountcreator import *
  File "/usr/local/lib/python2.7/site-packages/pikaptcha/accountcreator.py", line 16, in <module>
    from seleniumrequests import Chrome
ImportError: No module named seleniumrequests

**Comment by Clamb94** [comment]
Same problem here on windows 10 64bit

**Comment by smc87** [comment]
temp fix:
pip install selenium-requests

**Comment by Ericwonne** [comment]
Same issue.
>>> import selenium-requests
SyntaxError: invalid syntax (the dash)

>>> import seleniumrequests
Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    import seleniumrequests
ModuleNotFoundError: No module named 'seleniumrequests'
